[package]
name = "moon_file_group"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "File groups and collections."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = true

[dependencies]
moon_common = { version = "0.0.9", path = "../common" }
moon_config = { version = "0.0.11", path = "../config" }
common-path = "1.0.0"
miette = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
starbase_utils = { workspace = true, features = ["glob"] }
thiserror = { workspace = true }

[dev-dependencies]
starbase_sandbox = { workspace = true }

[lints]
workspace = true
